defmodule Helpdesk.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      remove :status
    end
  end

  def down do
    alter table(:tickets) do
      add :status, :text, null: false, default: "state_a"
    end
  end
end
